
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SUBSTRING = 49;
  public static final int QUERY = 41;
  public static final int POW = 17;
  public static final int CHAR = 58;
  public static final int GE = 24;
  public static final int CONCAT = 30;
  public static final int READINT = 53;
  public static final int CAR = 43;
  public static final int CASE = 40;
  public static final int INTEGER = 55;
  public static final int CDR = 44;
  public static final int LPAREN = 2;
  public static final int SEMI = 8;
  public static final int PRINTLN = 51;
  public static final int MINUS = 13;
  public static final int RPAREN = 3;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int LT = 23;
  public static final int NIL = 54;
  public static final int OR = 28;
  public static final int COMMA = 10;
  public static final int LAZY = 33;
  public static final int CALL = 32;
  public static final int COMP = 20;
  public static final int DIV = 15;
  public static final int PLUS = 12;
  public static final int IF = 37;
  public static final int ASSIGN = 35;
  public static final int DOT = 11;
  public static final int LE = 25;
  public static final int BOOLEAN = 60;
  public static final int EOF = 0;
  public static final int SIZE = 46;
  public static final int error = 1;
  public static final int BITOR = 19;
  public static final int MUL = 14;
  public static final int MOD = 16;
  public static final int NEQ = 26;
  public static final int PAIR = 42;
  public static final int EQ = 21;
  public static final int LBRACK = 4;
  public static final int REAL = 56;
  public static final int EQV = 47;
  public static final int COLON = 9;
  public static final int ELSE = 39;
  public static final int LBRACE = 6;
  public static final int VARIABLE = 57;
  public static final int READ = 52;
  public static final int RBRACK = 5;
  public static final int EQL = 48;
  public static final int LIST = 45;
  public static final int LET = 36;
  public static final int THEN = 38;
  public static final int RBRACE = 7;
  public static final int BITAND = 18;
  public static final int STRING = 59;
  public static final int PROC = 31;
  public static final int DEF = 34;
  public static final int GT = 22;
  public static final int PRINT = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COLON",
  "COMMA",
  "DOT",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "BITAND",
  "BITOR",
  "COMP",
  "EQ",
  "GT",
  "LT",
  "GE",
  "LE",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "CONCAT",
  "PROC",
  "CALL",
  "LAZY",
  "DEF",
  "ASSIGN",
  "LET",
  "IF",
  "THEN",
  "ELSE",
  "CASE",
  "QUERY",
  "PAIR",
  "CAR",
  "CDR",
  "LIST",
  "SIZE",
  "EQV",
  "EQL",
  "SUBSTRING",
  "PRINT",
  "PRINTLN",
  "READ",
  "READINT",
  "NIL",
  "INTEGER",
  "REAL",
  "VARIABLE",
  "CHAR",
  "STRING",
  "BOOLEAN"
  };
}

